### ISSUE TITLE
启动创世节点报错

### ISSUE THREAD

**Issue by caokun8008** [filecoin-project/community-china#53]
init set f3ur3pvhohzi5c4nf7shaix5ygwcxhwvlc6gotbl5zrf364cjbwj6uuparmo6x7htnuozoih7rhjj4bn455lpa t0100
init set f1ceb34gnsc6qk5dt6n7xg6ycwzasjhbxm3iylkiy t0101
2021-03-30T20:43:30.146+0800	WARN	vm	vm/runtime.go:332	Abortf: Allowance 4096 below MinVerifiedDealSize for add verifier f081
2021-03-30T20:43:30.146+0800	WARN	vm	vm/runtime.go:145	VM.Call failure: Allowance 4096 below MinVerifiedDealSize for add verifier f081 (RetCode=16):
    github.com/filecoin-project/specs-actors/actors/builtin/verifreg.Actor.AddVerifier
        /root/go/pkg/mod/github.com/filecoin-project/specs-actors@v0.9.13/actors/builtin/verifreg/verified_registry_actor.go:70
ERROR: initializing node: starting node: could not build arguments for function "github.com/filecoin-project/lotus/node/modules/lp2p".StartListening.func1 (/data/filecoin/lotus/node/modules/lp2p/addrs.go:98): failed to build host.Host: could not build arguments for function "reflect".makeFuncStub (/usr/local/go/src/reflect/asm_amd64.s:12): failed to build lp2p.BaseIpfsRouting: could not build arguments for function "reflect".makeFuncStub (/usr/local/go/src/reflect/asm_amd64.s:12): failed to build dtypes.NetworkName: could not build arguments for function "reflect".makeFuncStub (/usr/local/go/src/reflect/asm_amd64.s:12): failed to build dtypes.AfterGenesisSet: received non-nil error from function "reflect".makeFuncStub (/usr/local/go/src/reflect/asm_amd64.s:12): genesis func failed: make genesis block: failed to verify presealed data: failed to create verifier: doExec apply message failed: Allowance 4096 below MinVerifiedDealSize for add verifier f081 (RetCode=16)

**Comment by NewMai** [comment]
https://github.com/filecoin-project/community-china/discussions/9

参考这个。
