### ISSUE TITLE
我们在招募做filecoin挖矿的技术，懂硬件懂系统挖矿优化和有经验的技术 欢迎联系 1021979490@qq.com

### ISSUE THREAD

**Issue by icedtea6** [filecoin-project/community-china#61]
我们在招募做filecoin挖矿的技术，懂硬件懂系统挖矿优化和有经验的技术 欢迎联系 wechat  :ITea1005

_Originally posted by @icedtea6 in https://github.com/filecoin-project/community-china/discussions/27_

**Comment by NewMai** [comment]
请在 讨论模块发布招聘信息。

https://github.com/filecoin-project/community-china/discussions/categories/%E4%BA%BA%E6%89%8D%E6%8B%9B%E8%81%98
